### ISSUE TITLE
Ungraceful failure if spotipy environment vars aren't setup

### ISSUE THREAD

**Issue by nickspeal** [nickspeal/musicThisWeek#1]
Error trace:

```
Please Log into Spotify
Username: nickspeal

            You need to set your Spotify API credentials. You can do this by
            setting environment variables like so:

            export SPOTIPY_CLIENT_ID='your-spotify-client-id'
            export SPOTIPY_CLIENT_SECRET='your-spotify-client-secret'
            export SPOTIPY_REDIRECT_URI='your-app-redirect-url'

            Get your credentials at     
                https://developer.spotify.com/my-applications

Traceback (most recent call last):
  File "musicThisWeek.py", line 26, in <module>
    error = pc.login("nickspeal")
  File "/Users/Nick/Coding/musicThisWeek/playlistCreator.py", line 57, in login
    token = util.prompt_for_user_token(self.username, scope)
  File "/Users/Nick/.virtualenvs/music/lib/python2.7/site-packages/spotipy/util.py", line 47, in prompt_for_user_token
    raise spotipy.SpotifyException(550, -1, 'no credentials set')
spotipy.client.SpotifyException: http status: 550, code:-1 - no credentials set
```

Workaround:
`source spotipyCreds.sh` before running the app.

**Comment by nickspeal** [comment]
This is an artifact of running locally. This won't affect a properly-configured server-side app.
